replication: update replication details to consider volume group
csi-addons/spec pull request #67
Opened 2024-06-18 12:03 UTC by Madhu-1

This PR contains the below changes
* Mark the volume_id as deprecated one
* Mark the volume_id in replication as optional
* Update the Error Scheme to consider the Replication Source instead of volume

2024-06-18 12:11 UTC, nixpanic requested changes

2024-06-18 12:11 UTC, nixpanic commented on replication/README.md
> +  string volume_id = 1 [deprecated = true];
please update the description, point out to use `replication_source` instead.

2024-06-19 08:05 UTC, yati1998 approved these changes

2024-06-19 08:26 UTC, nixpanic requested changes

2024-06-19 08:45 UTC, nixpanic approved these changes

2024-06-19 10:17 UTC, iPraveenParihar approved these changes
Thanks!

2024-06-19 10:31 UTC, yati1998 approved these changes

2024-06-19 10:36 UTC, Rakshith-R approved these changes

2024-06-19 10:37 UTC, merged